module.exports = {
	DOCS: "\n"+
			"//********* JADEMODULES v 0.1 ********* \n" + 
			"//********* DO not edit this file ********* \n",
	HEADER: "\n//#\n",
	HEADER_MIXIN: "\n//#Mixinified content\n",
	INCLUDES: "\nrequire lib/jm\n"
}